AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  juhoappi

Parameters:
  AppBucketName:
    Type: String
    Description: "REQUIRED: Unique S3 bucket name to use for the app."
    Default: jnupponen-scraper

Resources:
  ScraperFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/scraper.scraper
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 60
      Policies:
        S3WritePolicy:
          BucketName: !Ref AppBucketName
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Enabled: True
      Environment:
        Variables:
          BUCKET: !Ref AppBucket


  AppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AppBucketName
